---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure sudorule is present with the given order.
  - freeipa.ansible_freeipa.ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      runasuser: admin
      action: member
