---
- name: Playbook to manage IPA role.
  hosts: ipaserver
  become: yes
  gather_facts: no

  tasks:
  - freeipa.ansible_freeipa.iparole:
      ipaadmin_password: SomeADMINpassword
      name: somerole
      description: A role in IPA.
